version: "3"
services:
    chrome:
        image: selenium/standalone-chrome
        container_name: chrome-selenium
        volumes: 
            - /dev/shm:/dev/shm
        ports: 
            - 4444:4444

